get http://localhost:3000/

### go home center of messenger application
get http://localhost:3000/home


#### go login page of messenger application
get http://localhost:3000/signin

### go log out page
POST  http://localhost:3000/signup
Content-Type: application/json

{
    "email":"phongkaster@gmail.com",
    "gender":"male",
    "password":"Forever21",
    "password_confirmation":"Forever21",
    "commit":"Tạo tài khoản"
}

