get http://localhost:3000/

### go home center of messenger application
get http://localhost:3000/home


#### go login page of messenger application
get http://localhost:3000/login

### go log out page
get http://localhost:3000/logout